import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "sl" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  sl: {
    // Header
    "nav.portfolio": "Portfolio",
    "nav.services": "Paketi",
    "nav.process": "Proces",
    "nav.faq": "FAQ",
    "nav.cta": "Želim spletno stran",
    "nav.cta.inquiry": "Pošlji povpraševanje",

    // Hero
    "hero.title1": "Zgradimo in vodimo",
    "hero.title2": "vašo spletno stran.",
    "hero.description": "Skrbimo za vašo spletno stran, da se vi lahko osredotočite na svoj posel.",
    "hero.cta": "Želim spletno stran",
    "hero.cta.inquiry": "Pošlji povpraševanje",
    "hero.cta.call": "Pokliči zdaj",
    "hero.available": "Na voljo 24/7",
    "hero.fast": "Jasna struktura",
    "hero.mobile": "Več povpraševanj",
    "hero.seo": "Pripravljeno za rast",
    
    // Inquiry form
    "inquiry.title": "Pošlji povpraševanje",
    "inquiry.nameLabel": "Ime in priimek",
    "inquiry.namePlaceholder": "Janez Novak",
    "inquiry.companyLabel": "Ime podjetja (opcijsko)",
    "inquiry.companyPlaceholder": "Ime podjetja",
    "inquiry.phoneLabel": "Telefonska številka",
    "inquiry.phonePlaceholder": "+386 40 123 456",
    "inquiry.emailLabel": "Email",
    "inquiry.emailPlaceholder": "janez@email.com",
    "inquiry.messageLabel": "Napiši nekaj o sebi in kaj potrebuješ",
    "inquiry.messagePlaceholder": "Na kratko opiši projekt, želje ali vprašanja.",
    "inquiry.submit": "Pošlji povpraševanje",
    "inquiry.submitting": "Pošiljam...",
    "inquiry.successTitle": "Hvala za povpraševanje!",
    "inquiry.successDescription": "Slišimo se v najkrajšem možnem času.",
    "inquiry.close": "Zapri",
    "inquiry.errorName": "Prosim vnesi ime in priimek.",
    "inquiry.errorPhone": "Prosim vnesi telefonsko številko.",
    "inquiry.errorEmail": "Prosim vnesi veljaven email naslov.",

    // CTA
    "cta.title": "Pripravljen/a na naslednji korak?",
    "cta.description": "Izpolni kratek vprašalnik ali nas pokliči — brez obveznosti.",
    "cta.button": "Izračunaj oceno cene",
    "cta.callButton": "Pokličite nas",

    // Portfolio
    "portfolio.title": "Primeri Strani",
    "portfolio.visualization": "Vizualizacija",
    "portfolio.demo": "Primeri so demonstracijski (demo projekti).",
    "portfolio.project1.description": "40% več povpraševanj v prvem mesecu",
    "portfolio.project2.description": "Moderna predstavitev arhitekturnega studia",
    "portfolio.project3.description": "E-trgovina z 25% konverzijo",
    "portfolio.project4.description": "MVP aplikacija za upravljanje projektov",
    "portfolio.project5.description": "Rezervacijski sistem za kliniko",
    "portfolio.project6.description": "Platforma za dostavo hrane",
    "portfolio.tag.landing": "Landing",
    "portfolio.tag.website": "Website",
    "portfolio.tag.store": "Trgovina",
    "portfolio.tag.mvp": "MVP",
    "portfolio.package.basic": "Osnovni paket",
    "portfolio.package.standard": "Standardni paket",
    "portfolio.package.advanced": "Napredni paket",

    // Pricing / Services
    "pricing.title": "Paketi",
    "pricing.subtitle": "Jasne rešitve. Prilagodljiv način plačila.",
    "pricing.toggleLabel": "Choose your payment option",
    "pricing.monthly": "Monthly",
    "pricing.onetime": "One-time",
    "pricing.recommended": "Most recommended",
    "pricing.monthlyNote": "Domena in hosting vključena · začetni strošek 20 €.",
    "pricing.onetimeNote": "Enkratna investicija · popolno lastništvo · brez naročnine.",
    "pricing.onetimeFooter": "Domena in hosting vključena.",
    "pricing.button.monthly": "Začni z mesečnim paketom",
    "pricing.from": "Od",
    "pricing.calculate": "Izračunaj ceno",
    "pricing.note": "Končna cena je odvisna od obsega in funkcionalnosti.",
    "pricing.landing": "Landing stran",
    "pricing.website": "Spletna stran",
    "pricing.store": "Spletna trgovina",
    "pricing.mvp": "Web / Mobile MVP",
    "pricing.feature.responsive": "Responsive dizajn",
    "pricing.feature.seo": "Osnovni SEO",
    "pricing.feature.gdpr": "GDPR osnove",
    "pricing.feature.fast": "Hitro nalaganje",
    "pricing.feature.subpages": "Več podstrani",
    "pricing.feature.fullstore": "Celotna trgovina",
    "pricing.feature.custom": "Razvoj po meri",

    // Process
    "process.title": "Kako poteka sodelovanje",
    "process.step": "Korak",
    "process.step1.title": "Kratek vprašalnik + cilj",
    "process.step1.description": "Izpolniš obrazec, da razumem tvoje potrebe in cilje projekta.",
    "process.step2.title": "Osnutek v 48–72 urah",
    "process.step2.description": "Pripravim prvi osnutek dizajna, ki ga skupaj pregledava.",
    "process.step3.title": "Popravki + objava + optimizacija",
    "process.step3.description": "Implementiram popravke, objavim stran in poskrbim za optimizacijo.",

    // Target Audience
    "target.title": "Za koga je to primerno",
    "target.benefit1": "želiš več povpraševanj",
    "target.benefit2": "ceniš jasen proces",
    "target.benefit3": "dostopna začetna investicija",
    "target.benefit4": "gradiš projekt za rast",

    // Collaboration
    "collab.title": "Kako poteka sodelovanje",
    "collab.step": "Korak",
    "collab.step1.title": "Uvodni kontakt in uskladitev",
    "collab.step1.description": "Preko povpraševanja ali klica razumemo tvoje cilje in obseg projekta.",
    "collab.step2.title": "Osnutek v 24–72 urah",
    "collab.step2.description": "Pripravimo prvi dizajn za pregled in mirno uskladitev.",
    "collab.step3.title": "Izvedba, objava in nadaljnja rast",
    "collab.step3.description": "Stran dodelamo, objavimo in jo pripravimo za dolgoročno uporabo.",
    "collab.note1": "brez presenečenj",
    "collab.note2": "jasen proces",
    "collab.note3": "fokus na rezultat",

    // FAQ
    "faq.title": "Pogosta vprašanja",
    "faq.q1": "Koliko časa traja izdelava spletne strani?",
    "faq.a1": "Čas izdelave je odvisen od izbranega paketa: Osnovni paket 1–3 dni, Standardni paket 1–5 dni, Napredni paket pa 1–2 tedna, glede na zahtevnost projekta.",
    "faq.q2": "Kaj vse je vključeno v ceno?",
    "faq.a2": "V ceno so vključeni: dizajn in postavitev strani, prilagoditev za mobilne naprave, osnovni SEO, gostovanje in osnovno vzdrževanje, podpora glede na izbrani paket.",
    "faq.q3": "Koliko popravkov je vključenih?",
    "faq.a3": "Število in pogostost popravkov je odvisna od paketa. Manjši popravki so vključeni, dodatne ali pogostejše spremembe pa se upoštevajo pri izračunu cene.",
    "faq.q4": "Ali moram sam pripraviti besedilo in slike?",
    "faq.a4": "Lahko, ni pa obvezno. Če imaš vse pripravljeno, je proces hitrejši. Če potrebuješ pomoč, lahko pomagam pri vsebini, strukturi in predlogih.",
    "faq.q5": "Kaj pa gostovanje in domena?",
    "faq.a5": "Gostovanje je vključeno v vse pakete. Domena je lahko tvoja ali jo uredim zate. Pri mesečnih paketih se ob začetku zaračuna enkratni strošek za vzpostavitev domene in gostovanja.",
    "faq.q9": "Ali lahko kasneje nadgradim paket?",
    "faq.a9": "Da. Paketi so zasnovani tako, da omogočajo enostavno nadgradnjo, ko projekt ali potrebe zrastejo.",
    "faq.q10": "Ali je povpraševanje zavezujoče?",
    "faq.a10": "Ne. Izračun in povpraševanje sta informativna. Odločitev sprejmeš šele, ko se dogovorimo o vseh podrobnostih.",

    // Footer
    "footer.description": "Spletne strani, ki prinašajo povpraševanja. Od ideje do online v nekaj dneh.",
    "footer.contact": "Kontakt",
    "footer.social": "Družbena omrežja",
    "footer.rights": "Vse pravice pridržane.",
    "footer.location": "Blagovica, Slovenija",

    // Form Page
    "form.pageTitle": "Želim spletno stran",
    "form.pageDescription": "Odgovori na nekaj vprašanj (2–3 minute). Na koncu vidiš oceno investicije.",
    "form.step1Title": "Korak 1/3 — Osnovno",
    "form.step2Title": "Korak 2/3 — Projekt",
    "form.step3Title": "Korak 3/3 — Funkcionalnosti + rok",
    "form.nameLabel": "Ime in priimek *",
    "form.namePlaceholder": "Janez Novak",
    "form.companyLabel": "Podjetje",
    "form.companyPlaceholder": "Ime podjetja (opcijsko)",
    "form.emailLabel": "Email *",
    "form.emailPlaceholder": "janez@email.com",
    "form.phoneLabel": "Telefon",
    "form.phonePlaceholder": "+386 40 123 456 (opcijsko)",
    "form.whatNeedLabel": "Kaj potrebuješ? *",
    "form.landing": "Landing stran",
    "form.landingPrice": "od 300 €",
    "form.website": "Spletna stran (več podstrani)",
    "form.websitePrice": "od 650 €",
    "form.store": "Spletna trgovina",
    "form.storePrice": "od 1.200 €",
    "form.mvp": "Web / Mobile MVP",
    "form.mvpPrice": "od 1.800 €",
    "form.subpagesLabel": "Koliko podstrani približno? *",
    "form.contentLabel": "Ali imaš pripravljena besedila in slike? *",
    "form.contentYes": "Da",
    "form.contentPartly": "Delno",
    "form.contentNo": "Ne",
    "form.featuresLabel": "Kaj mora stran imeti?",
    "form.featureContact": "Kontaktni obrazec",
    "form.featureBooking": "Rezervacije / booking",
    "form.featureBlog": "Blog",
    "form.featureLanguages": "Več jezikov",
    "form.featureNewsletter": "Newsletter",
    "form.featurePayments": "Plačila (trgovina)",
    "form.featureLogin": "Login / uporabniški računi",
    "form.deadlineLabel": "Kdaj želiš stran online? *",
    "form.deadline2_4": "2–4 tedne",
    "form.deadline7_10": "7–10 dni",
    "form.deadlineAsap": "ASAP (3–5 dni)",
    "form.additionalLabel": "Dodatno",
    "form.additionalPlaceholder": "Povej mi še kaj o projektu / linki primerov",
    "form.priceEstimate": "Ocena investicije",
    "form.priceApprox": "Približna cena:",
    "form.priceNote": "Končna cena se potrdi po kratkem klicu.",
    "form.back": "Nazaj",
    "form.next": "Naprej",
    "form.submit": "Pošlji povpraševanje",
    "form.submitting": "Pošiljam...",
    "form.successTitle": "Hvala! Povpraševanje je poslano.",
    "form.successDescription": "Odgovorim v 24 urah.",
    "form.backHome": "Nazaj na domačo stran",
    "form.errorName": "Prosim vnesi ime in priimek.",
    "form.errorEmail": "Prosim vnesi veljaven email naslov.",
    "form.errorWhat": "Prosim izberi kaj potrebuješ.",
    "form.errorSubpages": "Prosim izberi število podstrani.",
    "form.errorContent": "Prosim izberi ali imaš pripravljeno vsebino.",
    "form.errorDeadline": "Prosim izberi želeni rok.",
    "form.errorGeneric": "Prišlo je do napake. Prosim poskusi ponovno.",
    "form.errorCaptcha": "Prosim potrdi, da nisi robot.",
    "form.captchaRequired": "Prosim potrdi, da nisi robot.",
    "form.error": "Napaka",
  },
  en: {
    // Header
    "nav.portfolio": "Portfolio",
    "nav.services": "Services",
    "nav.process": "Process",
    "nav.faq": "FAQ",
    "nav.cta": "I want a website",
    "nav.cta.inquiry": "Send inquiry",

    // Hero
    "hero.title1": "We build and manage",
    "hero.title2": "your website.",
    "hero.description": "Join businesses that leave the web to us and focus on their business.",
    "hero.cta": "I want a website",
    "hero.cta.inquiry": "Send inquiry",
    "hero.cta.call": "Call now",
    "hero.available": "Available 24/7",
    "hero.fast": "Fast",
    "hero.mobile": "Mobile-first",
    "hero.seo": "SEO basics",
    
    // Inquiry form
    "inquiry.title": "Send inquiry",
    "inquiry.nameLabel": "Full name",
    "inquiry.namePlaceholder": "John Doe",
    "inquiry.companyLabel": "Company name (optional)",
    "inquiry.companyPlaceholder": "Company name",
    "inquiry.phoneLabel": "Phone number",
    "inquiry.phonePlaceholder": "+1 234 567 890",
    "inquiry.emailLabel": "Email",
    "inquiry.emailPlaceholder": "john@email.com",
    "inquiry.messageLabel": "Tell us about yourself and what you need",
    "inquiry.messagePlaceholder": "Briefly describe your project, goals, or questions.",
    "inquiry.submit": "Send inquiry",
    "inquiry.submitting": "Sending...",
    "inquiry.successTitle": "Thank you for your inquiry!",
    "inquiry.successDescription": "We will get back to you as soon as possible.",
    "inquiry.close": "Close",
    "inquiry.errorName": "Please enter your full name.",
    "inquiry.errorPhone": "Please enter your phone number.",
    "inquiry.errorEmail": "Please enter a valid email address.",

    // CTA
    "cta.title": "Ready for the next step?",
    "cta.description": "Fill out a short questionnaire or call us — no obligations.",
    "cta.button": "Calculate price estimate",
    "cta.callButton": "Call us",

    // Portfolio
    "portfolio.title": "Our projects",
    "portfolio.visualization": "Visualization",
    "portfolio.demo": "Examples are demonstration (demo projects).",
    "portfolio.project1.description": "40% more inquiries in the first month",
    "portfolio.project2.description": "Modern presentation of an architecture studio",
    "portfolio.project3.description": "E-commerce with 25% conversion",
    "portfolio.project4.description": "MVP app for project management",
    "portfolio.project5.description": "Booking system for a clinic",
    "portfolio.project6.description": "Food delivery platform",
    "portfolio.tag.landing": "Landing",
    "portfolio.tag.website": "Website",
    "portfolio.tag.store": "Store",
    "portfolio.tag.mvp": "MVP",
    "portfolio.package.basic": "Basic package",
    "portfolio.package.standard": "Standard package",
    "portfolio.package.advanced": "Advanced package",

    // Pricing / Services
    "pricing.title": "Packages",
    "pricing.subtitle": "Clear solutions. Flexible payment options.",
    "pricing.toggleLabel": "Choose your payment option",
    "pricing.monthly": "Monthly",
    "pricing.onetime": "One-time",
    "pricing.recommended": "Most recommended",
    "pricing.monthlyNote": "Domain and hosting included · setup fee €20.",
    "pricing.onetimeNote": "One-time investment · full ownership · no subscription.",
    "pricing.onetimeFooter": "Domain and hosting included.",
    "pricing.button.monthly": "Start with monthly plan",
    "pricing.from": "From",
    "pricing.calculate": "Calculate price",
    "pricing.note": "Final price depends on scope and functionality.",
    "pricing.landing": "Landing page",
    "pricing.website": "Website",
    "pricing.store": "E-commerce",
    "pricing.mvp": "Web / Mobile MVP",
    "pricing.feature.responsive": "Responsive design",
    "pricing.feature.seo": "Basic SEO",
    "pricing.feature.gdpr": "GDPR basics",
    "pricing.feature.fast": "Fast loading",
    "pricing.feature.subpages": "Multiple subpages",
    "pricing.feature.fullstore": "Full store",
    "pricing.feature.custom": "Custom development",

    // Process
    "process.title": "How collaboration works",
    "process.step": "Step",
    "process.step1.title": "Short questionnaire + goal",
    "process.step1.description": "Fill out the form so I understand your needs and project goals.",
    "process.step2.title": "Draft in 48–72 hours",
    "process.step2.description": "I prepare the first design draft, which we review together.",
    "process.step3.title": "Revisions + launch + optimization",
    "process.step3.description": "I implement revisions, launch the site, and take care of optimization.",

    // Target Audience
    "target.title": "Who is this for",
    "target.benefit1": "you want more inquiries",
    "target.benefit2": "you value a clear process",
    "target.benefit3": "accessible initial investment",
    "target.benefit4": "you're building for growth",

    // Collaboration
    "collab.title": "How collaboration works",
    "collab.step": "Step",
    "collab.step1.title": "Initial contact and alignment",
    "collab.step1.description": "Through an inquiry or call, we understand your goals and project scope.",
    "collab.step2.title": "Draft in 24–72 hours",
    "collab.step2.description": "We prepare the first design for review and calm alignment.",
    "collab.step3.title": "Implementation, launch and ongoing growth",
    "collab.step3.description": "We refine the site, publish it, and prepare it for long-term use.",
    "collab.note1": "no surprises",
    "collab.note2": "clear process",
    "collab.note3": "focus on results",

    // FAQ
    "faq.title": "Frequently asked questions",
    "faq.q1": "How long does it take to build a website?",
    "faq.a1": "Production time depends on the selected package: Basic package 1–3 days, Standard package 1–5 days, Advanced package 1–2 weeks, depending on project complexity.",
    "faq.q2": "What is included in the price?",
    "faq.a2": "The price includes: design and layout, mobile responsiveness, basic SEO, hosting and basic maintenance, support based on the selected package. Final price is determined by the options selected in the calculator.",
    "faq.q3": "How many revisions are included?",
    "faq.a3": "The number and frequency of revisions depends on the package. Minor changes are included, additional or more frequent changes are factored into the price calculation.",
    "faq.q4": "Do I need to prepare text and images myself?",
    "faq.a4": "You can, but it's not required. If you have everything ready, the process is faster. If you need help, I can assist with content, structure, and suggestions.",
    "faq.q5": "What about hosting and domain?",
    "faq.a5": "Hosting is included in all packages. The domain can be yours or I can set it up for you. For monthly packages, a one-time setup fee for domain and hosting is charged at the start.",
    "faq.q9": "Can I upgrade my package later?",
    "faq.a9": "Yes. Packages are designed for easy upgrades as your project or needs grow.",
    "faq.q10": "Is the inquiry binding?",
    "faq.a10": "No. The calculation and inquiry are informational. You only decide once we agree on all the details.",

    // Footer
    "footer.description": "Websites that generate leads. From idea to online in a few days.",
    "footer.contact": "Contact",
    "footer.social": "Social Media",
    "footer.rights": "All rights reserved.",
    "footer.location": "Blagovica, Slovenia",

    // Form Page
    "form.pageTitle": "I want a website",
    "form.pageDescription": "Answer a few questions (2–3 minutes). At the end, you'll see an investment estimate.",
    "form.step1Title": "Step 1/3 — Basics",
    "form.step2Title": "Step 2/3 — Project",
    "form.step3Title": "Step 3/3 — Features + timeline",
    "form.nameLabel": "Full name *",
    "form.namePlaceholder": "John Doe",
    "form.companyLabel": "Company",
    "form.companyPlaceholder": "Company name (optional)",
    "form.emailLabel": "Email *",
    "form.emailPlaceholder": "john@email.com",
    "form.phoneLabel": "Phone",
    "form.phonePlaceholder": "+1 234 567 890 (optional)",
    "form.whatNeedLabel": "What do you need? *",
    "form.landing": "Landing page",
    "form.landingPrice": "from €300",
    "form.website": "Website (multiple pages)",
    "form.websitePrice": "from €650",
    "form.store": "E-commerce store",
    "form.storePrice": "from €1,200",
    "form.mvp": "Web / Mobile MVP",
    "form.mvpPrice": "from €1,800",
    "form.subpagesLabel": "Approximately how many subpages? *",
    "form.contentLabel": "Do you have text and images ready? *",
    "form.contentYes": "Yes",
    "form.contentPartly": "Partly",
    "form.contentNo": "No",
    "form.featuresLabel": "What should the site include?",
    "form.featureContact": "Contact form",
    "form.featureBooking": "Reservations / booking",
    "form.featureBlog": "Blog",
    "form.featureLanguages": "Multiple languages",
    "form.featureNewsletter": "Newsletter",
    "form.featurePayments": "Payments (store)",
    "form.featureLogin": "Login / user accounts",
    "form.deadlineLabel": "When do you want the site online? *",
    "form.deadline2_4": "2–4 weeks",
    "form.deadline7_10": "7–10 days",
    "form.deadlineAsap": "ASAP (3–5 days)",
    "form.additionalLabel": "Additional",
    "form.additionalPlaceholder": "Tell me more about the project / example links",
    "form.priceEstimate": "Investment estimate",
    "form.priceApprox": "Approximate price:",
    "form.priceNote": "Final price confirmed after a short call.",
    "form.back": "Back",
    "form.next": "Next",
    "form.submit": "Submit inquiry",
    "form.submitting": "Submitting...",
    "form.successTitle": "Thank you! Inquiry submitted.",
    "form.successDescription": "I'll respond within 24 hours.",
    "form.backHome": "Back to home",
    "form.errorName": "Please enter your full name.",
    "form.errorEmail": "Please enter a valid email address.",
    "form.errorWhat": "Please select what you need.",
    "form.errorSubpages": "Please select the number of subpages.",
    "form.errorContent": "Please select if you have content ready.",
    "form.errorDeadline": "Please select your desired timeline.",
    "form.errorGeneric": "An error occurred. Please try again.",
    "form.errorCaptcha": "Please verify that you are not a robot.",
    "form.captchaRequired": "Please verify that you are not a robot.",
    "form.error": "Error",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "sl" || saved === "en") ? saved : "sl";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};